# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call(`_kkmeans_timesTwo`, x)
}

kkmeans <- function(data, k, kern, param, iter_max) {
    .Call(`_kkmeans_kkmeans`, data, k, kern, param, iter_max)
}

